import { Injectable } from '@angular/core';
import { StaffMember } from 'src/app/models/staff-member.model';

@Injectable({
  providedIn: 'root'
})
export class StaffService {
  staffMembers: StaffMember[] = [
    {
      id: 1,
      title: "dr. sc.",
      firstName: "Jasmin",
      lastName: "Velagić",
      position: "Redovni profesor",
      department: "Automatika i elektronika",
      email: "jasmin.velagic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/jasmin.velagic.en.pdf",
      specialTitle: "Dekan Elektrotehničkog fakulteta u Sarajevu"
    },
    {
      id: 2,
      title: "dr. sc.",
      firstName: "Selma",
      lastName: "Hanjalić",
      position: "Docent",
      department: "Elektroenergetika",
      email: "selma.hanjalic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/selma.hanjalic.en.pdf",
      specialTitle: "Prodekan za finansije"
    },
    {
      id: 3,
      title: "dr. sc.",
      firstName: "Željko",
      lastName: "Jurić",
      position: "Vanredni profesor",
      department: "Računarstvo i informatika",
      email: "zeljko.juric@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/zeljko.juric.en.pdf",
      specialTitle: "Prodekan za nastavu"
    },
    {
      id: 4,
      title: "dr. sc.",
      firstName: "Tarik",
      lastName: "Uzunović",
      position: "Docent",
      department: "Automatika i elektronika",
      email: "tarik.uzunovic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/tarik.uzunovic.en.pdf",
      specialTitle: "Prodekan za naučna istraživanja"
    },
    {
      id: 5,
      title: "dr. sc.",
      firstName: "Melita",
      lastName: "Ahić-Đokić",
      position: "Emeritus profesor",
      department: "Automatika i elektronika",
      email: "melita.ahic-dokic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/melita.ahic-dokic.en.pdf",
    },
    {
      id: 6,
      title: "acc. dr. sc.",
      firstName: "Zijo",
      lastName: "Pašić",
      position: "Emeritus profesor",
      department: "Automatika i elektronika",
      email: "zijo.pasic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/zijo.pasic.en.pdf",
    },
    {
      id: 7,
      title: "acc. dr. sc.",
      firstName: "Branislava",
      lastName: "Peruničić",
      position: "Emeritus profesor",
      department: "Automatika i elektronika",
      email: "branislava.perunicic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/branislava.perunicic.en.pdf",
    },
    {
      id: 8,
      title: "dr. sc.",
      firstName: "Adnan",
      lastName: "Salihbegović",
      position: "Emeritus profesor",
      department: "Automatika i elektronika",
      email: "adnan.salihbegovic@etf.unsa.ba",
      phone: "+387 33 250 700",
      fax: "+387 33 250 725",
      cv: "http://www.etf.unsa.ba/people/cv/adnan.salihbegovic.en.pdf",
    },
    {
      "id": 9,
      "title": "dr. sc.",
      "firstName": "Zikrija",
      "lastName": "Avdagić",
      "department": "Računarstvo i informatika",
      "position": "Redovni profesor",
      "email": "zikrija.avdagic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zikrija.avdagic.en.pdf"
    },
    {
      "id": 10,
      "title": "dr. sc.",
      "firstName": "Muharem",
      "lastName": "Avdispahić",
      "position": "Redovni profesor",
      "department": "Elektroenergetika",
      "email": "muharem.avdispahic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/muharem.avdispahic.en.pdf"
    },
    {
      "id": 11,
      "title": "dr. sc.",
      "firstName": "Dženana",
      "lastName": "Đonko",
      "position": "Redovni profesor",
      "department": "Računarstvo i informatika",
      "email": "dzenana.donko@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dzenana.donko.en.pdf"
    },
    {
      "id": 12,
      "title": "dr. sc.",
      "firstName": "Izudin",
      "lastName": "Džafić",
      "position": "Redovni profesor",
      "department": "Automatika i elektronika",
      "email": "izudin.dzafic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/izudin.dzafic.en.pdf"
    },
    {
      "id": 13,
      "title": "dr. sc.",
      "firstName": "Mesud",
      "lastName": "Hadžialić",
      "position": "Redovni profesor",
      "department": "Telekomunikacije",
      "email": "mesud.hadzialic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mesud.hadzialic.en.pdf"
    },
    {
      "id": 14,
      "title": "dr. sc.",
      "firstName": "Mujo",
      "lastName": "Hebibović",
      "position": "Redovni profesor",
      "department": "Automatika i elektronika",
      "email": "mujo.hebibovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mujo.hebibovic.en.pdf"
    },
    {
      "id": 15,
      "title": "dr. sc.",
      "firstName": "Mirsad",
      "lastName": "Kapetanović",
      "position": "Redovni profesor",
      "department": "Elektroenergetika",
      "email": "mirsad.kapetanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirsad.kapetanovic.en.pdf"
    },
    {
      "id": 16,
      "title": "dr. sc.",
      "firstName": "Vladimir",
      "lastName": "Lipovac",
      "position": "Redovni profesor",
      "department": "Telekomunikacije",
      "email": "vladimir.lipovac@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vladimir.lipovac.en.pdf"
    },
    {
      "id": 17,
      "title": "dr. sc.",
      "firstName": "Šemsudin",
      "lastName": "Mašić",
      "position": "Redovni profesor",
      "department": "Elektroenergetika",
      "email": "semsudin.masic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/semsudin.masic.en.pdf"
    },
    {
      "id": 18,
      "title": "dr. sc.",
      "firstName": "Mustafa",
      "lastName": "Musić",
      "position": "Redovni profesor",
      "department": "Automatika i elektronika",
      "email": "mustafa.music@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mustafa.music.en.pdf"
    },
    {
      "id": 19,
      "title": "dr. sc.",
      "firstName": "Novica",
      "lastName": "Nosović",
      "position": "Redovni profesor",
      "department": "Računarstvo i informatika",
      "email": "novica.nosovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/novica.nosovic.en.pdf"
    },
    {
      "id": 20,
      "title": "dr. sc.",
      "firstName": "Alma",
      "lastName": "Omerspahić",
      "position": "Redovni profesor",
      "department": "Automatika i elektronika",
      "email": "alma.omerspahic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/alma.omerspahic.en.pdf"
    },
    {
      "id": 21,
      "title": "dr. sc.",
      "firstName": "Hasnija",
      "lastName": "Šamić",
      "position": "Redovni profesor",
      "department": "Elektroenergetika",
      "email": "hasnija.samic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/hasnija.samic.en.pdf"
    },
    {
      "id": 22,
      "title": "dr. sc.",
      "firstName": "Šefko",
      "lastName": "Šikalo",
      "position": "Redovni profesor",
      "department": "Automatika i elektronika",
      "email": "sefko.sikalo@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sefko.sikalo.en.pdf"
    },
    {
      "id": 23,
      "title": "dr. sc.",
      "firstName": "Mirko",
      "lastName": "Škrbić",
      "position": "Redovni profesor",
      "department": "Telekomunikacije",
      "email": "mirko.skrbic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirko.skrbic.en.pdf"
    },
    {
      "id": 24,
      "title": "dr. sc.",
      "firstName": "Haris",
      "lastName": "Šupić",
      "position": "Redovni profesor",
      "department": "Računarstvo i informatika",
      "email": "haris.supic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/haris.supic.en.pdf"
    },
    {
      "id": 25,
      "title": "dr. sc.",
      "firstName": "Hamid",
      "lastName": "Zildžo",
      "position": "Redovni profesor",
      "department": "Elektroenergetika",
      "email": "hamid.zildzo@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/hamid.zildzo.en.pdf"
    },
    {
      "id": 26,
      "title": "dr. sc.",
      "firstName": "Abdulah",
      "lastName": "Akšamović",
      "position": "Vanredni profesor",
      "department": "Automatika i elektronika",
      "email": "abdulah.aksamovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/abdulah.aksamovic.en.pdf"
    },
    {
      "id": 27,
      "title": "dr. sc.",
      "firstName": "Zijad",
      "lastName": "Bajramović",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "zijad.bajramovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zijad.bajramovic.en.pdf"
    },
    {
      "id": 28,
      "title": "dr. sc.",
      "firstName": "Jasmina",
      "lastName": "Baraković-Husić",
      "position": "Vanredni profesor",
      "department": "Telekomunikacije",
      "email": "jasmina.barakovic-husic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/jasmina.barakovic-husic.en.pdf"
    },
    {
      "id": 29,
      "title": "dr. sc.",
      "firstName": "Smajo",
      "lastName": "Bišanović",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "smajo.bisanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/smajo.bisanovic.en.pdf"
    },
    {
      "id": 30,
      "title": "dr. sc.",
      "firstName": "Nasuf",
      "lastName": "Hadžiahmetović",
      "department": "Telekomunikacije",
      "position": "Vanredni profesor",
      "email": "nasuf.hadziahmetovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nasuf.hadziahmetovic.en.pdf"
    },
    {
      "id": 31,
      "title": "dr. sc.",
      "firstName": "Kemal",
      "lastName": "Hajdarević",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "kemal.hajdarevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kemal.hajdarevic.en.pdf"
    },
    {
      "id": 32,
      "title": "dr. sc.",
      "firstName": "Almir",
      "lastName": "Karabegović",
      "department": "Računarstvo i informatika",
      "position": "Vanredni profesor",
      "email": "almir.karabegovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almir.karabegovic.en.pdf"
    },
    {
      "id": 33,
      "title": "dr. sc.",
      "firstName": "Tatjana",
      "lastName": "Konjić",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "tatjana.konjic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/tatjana.konjic.en.pdf"
    },
    {
      "id": 34,
      "title": "dr. sc.",
      "firstName": "Samim",
      "lastName": "Konjicija",
      "position": "Vanredni profesor",
      "department": "Automatika i elektronika",
      "email": "samim.konjicija@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/samim.konjicija.en.pdf"
    },
    {
      "id": 35,
      "title": "dr. sc.",
      "firstName": "Bakir",
      "lastName": "Lačević",
      "position": "Vanredni profesor",
      "department": "Automatika i elektronika",
      "email": "bakir.lacevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/bakir.lacevic.en.pdf"
    },
    {
      "id": 36,
      "title": "dr. sc.",
      "firstName": "Saša",
      "lastName": "Mrdović",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "sasa.mrdovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sasa.mrdovic.en.pdf"
    },
    {
      "id": 37,
      "title": "dr. sc.",
      "firstName": "Amela",
      "lastName": "Muratović-ribic",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "amela.muratovic-ribic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/amela.muratovic-ribic.en.pdf"
    },
    {
      "id": 38,
      "title": "dr. sc.",
      "firstName": "Almasa",
      "lastName": "Odžak",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "almasa.odzak@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almasa.odzak.en.pdf"
    },
    {
      "id": 39,
      "title": "dr. sc.",
      "firstName": "Samir",
      "lastName": "Omanović",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "samir.omanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/samir.omanovic.en.pdf"
    },
    {
      "id": 40,
      "title": "dr. sc.",
      "firstName": "Samir",
      "lastName": "Ribić",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "samir.ribic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/samir.ribic.en.pdf"
    },
    {
      "id": 41,
      "title": "dr. sc.",
      "firstName": "Selma",
      "lastName": "Rizvić",
      "position": "Vanredni profesor",
      "department": "Računarstvo i informatika",
      "email": "selma.rizvic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/selma.rizvic.en.pdf"
    },
    {
      "id": 42,
      "title": "dr. sc.",
      "firstName": "Senad",
      "lastName": "Smaka",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "senad.smaka@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/senad.smaka.en.pdf"
    },
    {
      "id": 43,
      "title": "dr. sc.",
      "firstName": "Adnan",
      "lastName": "Tahirović",
      "position": "Vanredni profesor",
      "department": "Automatika i elektronika",
      "email": "adnan.tahirovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.tahirovic.en.pdf"
    },
    {
      "id": 44,
      "title": "dr. sc.",
      "firstName": "Irfan",
      "lastName": "Turković",
      "position": "Vanredni profesor",
      "department": "Elektroenergetika",
      "email": "irfan.turkovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/irfan.turkovic.en.pdf"
    },
    {
      "id": 45,
      "title": "dr. sc.",
      "firstName": "Amila",
      "lastName": "Akagić",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "amila.akagic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/amila.akagic.en.pdf"
    },
    {
      "id": 46,
      "title": "dr. sc.",
      "firstName": "Samir",
      "lastName": "Avdaković",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "samir.avdakovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/samir.avdakovic.en.pdf"
    },
    {
      "id": 47,
      "title": "dr. sc.",
      "firstName": "Mirza",
      "lastName": "Batalović",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "mirza.batalovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirza.batalovic.en.pdf"
    },
    {
      "id": 48,
      "title": "dr. sc.",
      "firstName": "Vedad",
      "lastName": "Bečirović",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "vedad.becirovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vedad.becirovic.en.pdf"
    },
    {
      "id": 49,
      "title": "dr. sc.",
      "firstName": "Alen",
      "lastName": "Begović",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "alen.begovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/alen.begovic.en.pdf"
    },
    {
      "id": 50,
      "title": "dr. sc.",
      "firstName": "Ingmar",
      "lastName": "Bešić",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "ingmar.besic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/ingmar.besic.en.pdf"
    },
    {
      "id": 51,
      "title": "dr. sc.",
      "firstName": "Dušanka",
      "lastName": "Bošković",
      "position": "Docent",
      "department": "Automatika i elektronika",
      "email": "dusanka.boskovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dusanka.boskovic.en.pdf"
    },
    {
      "id": 52,
      "title": "dr. sc.",
      "firstName": "Emir",
      "lastName": "Buza",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "emir.buza@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.buza.en.pdf"
    },
    {
      "id": 53,
      "title": "dr. sc.",
      "firstName": "Selma",
      "lastName": "Grebović",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "selma.grebovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/selma.grebovic.en.pdf"
    },
    {
      "id": 54,
      "title": "dr. sc.",
      "firstName": "Adnan",
      "lastName": "Huremović",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "adnan.huremovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.huremovic.en.pdf"
    },
    {
      "id": 55,
      "title": "dr. sc.",
      "firstName": "Senad",
      "lastName": "Huseinbegović",
      "position": "Docent",
      "department": "Automatika i elektronika",
      "email": "senad.huseinbegovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/senad.huseinbegovic.en.pdf"
    },
    {
      "id": 56,
      "title": "dr. sc.",
      "firstName": "Kemal",
      "lastName": "Huseinović",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "kemal.huseinovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kemal.huseinovic.en.pdf"
    },
    {
      "id": 57,
      "title": "dr. sc.",
      "firstName": "Vedran",
      "lastName": "Ljubović",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "vedran.ljubovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vedran.ljubovic.en.pdf"
    },
    {
      "id": 58,
      "title": "dr. sc.",
      "firstName": "Miralem",
      "lastName": "Mehić",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "miralem.mehic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/miralem.mehic.en.pdf"
    },
    {
      "id": 59,
      "title": "dr. sc.",
      "firstName": "Adnan",
      "lastName": "Mujezinović",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "adnan.mujezinovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.mujezinovic.en.pdf"
    },
    {
      "id": 60,
      "title": "dr. sc.",
      "firstName": "Pamela",
      "lastName": "Njemčević",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "pamela.njemcevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/pamela.njemcevic.en.pdf"
    },
    {
      "id": 61,
      "title": "dr. sc.",
      "firstName": "Vensada",
      "lastName": "Okanović",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "vensada.okanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vensada.okanovic.en.pdf"
    },
    {
      "id": 62,
      "title": "dr. sc.",
      "firstName": "Dinko",
      "lastName": "Osmanković",
      "position": "Docent",
      "department": "Automatika i elektronika",
      "email": "dinko.osmankovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dinko.osmankovic.en.pdf"
    },
    {
      "id": 63,
      "title": "dr. sc.",
      "firstName": "Zenan",
      "lastName": "Šabanac",
      "position": "Docent",
      "department": "Elektroenergetika",
      "email": "zenan.sabanac@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zenan.sabanac.en.pdf"
    },
    {
      "id": 64,
      "title": "dr. sc.",
      "firstName": "Emir",
      "lastName": "Sokić",
      "position": "Docent",
      "department": "Automatika i elektronika",
      "email": "emir.sokic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.sokic.en.pdf"
    },
    {
      "id": 65,
      "title": "dr. sc.",
      "firstName": "Anel",
      "lastName": "Tanović",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "anel.tanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/anel.tanovic.en.pdf"
    },
    {
      "id": 66,
      "title": "dr. sc.",
      "firstName": "Emir",
      "lastName": "Turajlić",
      "position": "Docent",
      "department": "Telekomunikacije",
      "email": "emir.turajlic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.turajlic.en.pdf"
    },
    {
      "id": 67,
      "title": "dr. sc.",
      "firstName": "Razija",
      "lastName": "Turčinhodžić",
      "position": "Docent",
      "department": "Računarstvo i informatika",
      "email": "razija.turcinhodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/razija.turcinhodzic.en.pdf"
    },
    {
      "id": 68,
      "title": "mr. sc.",
      "firstName": "Lejla",
      "lastName": "Ahmethodžić",
      "position": "Viši asistent",
      "department": "Automatika i elektronika",
      "email": "lejla.ahmethodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/lejla.ahmethodzic.en.pdf"
    },
    {
      "id": 69,
      "firstName": "Mehmed",
      "lastName": "Brkić",
      "position": "Viši asistent",
      "department": "Automatika i elektronika",
      "email": "mehmed.brkic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mehmed.brkic.en.pdf"
    },
    {
      "id": 70,
      "firstName": "Enio",
      "lastName": "Kaljić",
      "position": "Viši asistent",
      "department": "Telekomunikacije",
      "email": "enio.kaljic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/enio.kaljic.en.pdf"
    },
    {
      "id": 71,
      "title": "mr. sc.",
      "firstName": "Almir",
      "lastName": "Salihbegović",
      "position": "Viši asistent",
      "department": "Automatika i elektronika",
      "email": "almir.salihbegovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almir.salihbegovic.en.pdf"
    },
    {
      "id": 72,
      "title": "mr. sc.",
      "firstName": "Mediha",
      "lastName": "Zukić",
      "position": "Viši asistent",
      "department": "Automatika i elektronika",
      "email": "mediha.zukic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mediha.zukic.en.pdf"
    },
    {
      "id": 73,
      "firstName": "Emir",
      "lastName": "Cogo",
      "position": "Asistent",
      "department": "Računarstvo i informatika",
      "email": "emir.cogo@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.cogo.en.pdf"
    },
    {
      "id": 74,
      "firstName": "Nermin",
      "lastName": "Čolo",
      "position": "Asistent",
      "department": "Automatika i elektronika",
      "email": "nermin.colo@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nermin.colo.en.pdf"
    },
    {
      "id": 75,
      "firstName": "Nedis",
      "lastName": "Dautbašić",
      "position": "Asistent",
      "department": "Elektroenergetika",
      "email": "nedis.dautbasic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nedis.dautbasic.en.pdf"
    },
    {
      "id": 76,
      "firstName": "Meliha",
      "lastName": "Dulić",
      "position": "Asistent",
      "department": "Telekomunikacije",
      "email": "meliha.dulic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/meliha.dulic.en.pdf"
    },
    {
      "id": 77,
      "firstName": "Hana",
      "lastName": "Haseljić",
      "position": "Asistent",
      "department": "Računarstvo i informatika",
      "email": "hana.haseljic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/hana.haseljic.en.pdf"
    },
    {
      "id": 78,
      "firstName": "Haris",
      "lastName": "Hasić",
      "position": "Asistent",
      "department": "Računarstvo i informatika",
      "email": "haris.hasic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/haris.hasic.en.pdf"
    },
    {
      "id": 79,
      "firstName": "Vahid",
      "lastName": "Helać",
      "position": "Asistent",
      "department": "Elektroenergetika",
      "email": "vahid.helac@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vahid.helac.en.pdf"
    },
    {
      "id": 80,
      "firstName": "Kerim",
      "lastName": "Hodžić",
      "position": "Asistent",
      "department": "Računarstvo i informatika",
      "email": "kerim.hodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kerim.hodzic.en.pdf"
    },
    {
      "id": 81,
      "firstName": "Vedran",
      "lastName": "Karahodžić",
      "position": "Asistent",
      "department": "Telekomunikacije",
      "email": "vedran.karahodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vedran.karahodzic.en.pdf"
    },
    {
      "id": 82,
      "firstName": "Almir",
      "lastName": "Marić",
      "position": "Asistent",
      "department": "Telekomunikacije",
      "email": "almir.maric@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almir.maric.en.pdf"
    },
    {
      "id": 83,
      "firstName": "Maja",
      "lastName": "Muftić-Dedović",
      "position": "Asistent",
      "department": "Elektroenergetika",
      "email": "maja.muftic-dedovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/maja.muftic-dedovic.en.pdf"
    },
    {
      "id": 84,
      "firstName": "Nermin",
      "lastName": "Oprašić",
      "position": "Asistent",
      "department": "Elektroenergetika",
      "email": "nermin.oprasic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nermin.oprasic.en.pdf"
    },
    {
      "id": 85,
      "firstName": "Adnan",
      "lastName": "Osmanović",
      "position": "Asistent",
      "department": "Automatika i elektronika",
      "email": "adnan.osmanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.osmanovic.en.pdf"
    },
    {
      "id": 86,
      "firstName": "Irfan",
      "lastName": "Prazina",
      "position": "Asistent",
      "department": "Računarstvo i informatika",
      "email": "irfan.prazina@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/irfan.prazina.en.pdf"
    },
    {
      "id": 87,
      "firstName": "Nina",
      "lastName": "Slamnik",
      "position": "Asistent",
      "department": "Telekomunikacije",
      "email": "nina.slamnik@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nina.slamnik.en.pdf"
    },
    {
      "id": 88,
      "firstName": "Zlatan",
      "lastName": "Tucaković",
      "position": "Asistent",
      "department": "Automatika i elektronika",
      "email": "zlatan.tucakovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zlatan.tucakovic.en.pdf"
    },
    {
      "id": 89,
      "firstName": "Jasmina",
      "lastName": "Zubača",
      "position": "Asistent",
      "department": "Automatika i elektronika",
      "email": "jasmina.zubaca@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/jasmina.zubaca.en.pdf"
    },
    {
      "id": 90,
      "firstName": "Adnan",
      "lastName": "Ademović",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "adnan.ademovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.ademovic.en.pdf"
    },
    {
      "id": 91,
      "firstName": "Hakija",
      "lastName": "Agić",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "hakija.agic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/hakija.agic.en.pdf"
    },
    {
      "id": 92,
      "firstName": "Nermina",
      "lastName": "Ahmić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "nermina.ahmic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nermina.ahmic.en.pdf"
    },
    {
      "id": 93,
      "firstName": "Dina",
      "lastName": "Alić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "dina.alic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dina.alic.en.pdf"
    },
    {
      "id": 94,
      "firstName": "Dino",
      "lastName": "Alić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "dino.alic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dino.alic.en.pdf"
    },
    {
      "id": 95,
      "firstName": "Ajdin",
      "lastName": "Alihodžić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "ajdin.alihodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/ajdin.alihodzic.en.pdf"
    },
    {
      "id": 96,
      "firstName": "Amer",
      "lastName": "Aščerić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "amer.asceric@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/amer.asceric.en.pdf"
    },
    {
      "id": 97,
      "title": "dr. sc.",
      "firstName": "Almir",
      "lastName": "Badnjević",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "almir.badnjevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almir.badnjevic.en.pdf"
    },
    {
      "id": 98,
      "title": "dr. sc.",
      "firstName": "Nihad",
      "lastName": "Borovina",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "nihad.borovina@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nihad.borovina.en.pdf"
    },
    {
      "id": 99,
      "firstName": "Emina",
      "lastName": "Bukva",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "emina.bukva@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emina.bukva.en.pdf"
    },
    {
      "id": 100,
      "firstName": "Lamija",
      "lastName": "Ćemalović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "lamija.cemalovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/lamija.cemalovic.en.pdf"
    },
    {
      "id": 101,
      "title": "mr. sc.",
      "firstName": "Ajla",
      "lastName": "Ćerimagić-Hasibović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "ajla.cerimagic-hasibovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/ajla.cerimagic-hasibovic.en.pdf"
    },
    {
      "id": 102,
      "title": "mr. sc.",
      "firstName": "Zoran",
      "lastName": "Cico",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "zoran.cico@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zoran.cico.en.pdf"
    },
    {
      "id": 103,
      "firstName": "Dean",
      "lastName": "Čupović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "dean.cupovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/dean.cupovic.en.pdf"
    },
    {
      "id": 104,
      "firstName": "Sabina",
      "lastName": "Dacić-Lepara",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "sabina.dacic-lepara@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sabina.dacic-lepara.en.pdf"
    },
    {
      "id": 105,
      "firstName": "Armin",
      "lastName": "Dajić",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "armin.dajic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/armin.dajic.en.pdf"
    },
    {
      "id": 106,
      "firstName": "Almir",
      "lastName": "Đedović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "almir.dedovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/almir.dedovic.en.pdf"
    },
    {
      "id": 107,
      "title": "dr. sc.",
      "firstName": "Kemal",
      "lastName": "Delić",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "kemal.delic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kemal.delic.en.pdf"
    },
    {
      "id": 108,
      "title": "mr. sc.",
      "firstName": "Sead",
      "lastName": "Delić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "sead.delic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sead.delic.en.pdf"
    },
    {
      "id": 109,
      "firstName": "Adnan",
      "lastName": "Dželihodžić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "adnan.dzelihodzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adnan.dzelihodzic.en.pdf"
    },
    {
      "id": 110,
      "firstName": "Kenan",
      "lastName": "Ekinović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "kenan.ekinovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kenan.ekinovic.en.pdf"
    },
    {
      "id": 111,
      "title": "mr. sc.",
      "firstName": "Emir",
      "lastName": "Fočo",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "emir.foco@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.foco.en.pdf"
    },
    {
      "id": 112,
      "firstName": "Zana",
      "lastName": "Garaplija",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "zana.garaplija@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zana.garaplija.en.pdf"
    },
    {
      "id": 113,
      "firstName": "Kenan",
      "lastName": "Halilović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "kenan.halilovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/kenan.halilovic.en.pdf"
    },
    {
      "id": 114,
      "title": "dr. sc.",
      "firstName": "Moamer",
      "lastName": "Hasanović",
      "position": "Stručnjak iz prakse",
      "department": "Telekomunikacije",
      "email": "moamer.hasanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/moamer.hasanovic.en.pdf"
    },
    {
      "id": 115,
      "firstName": "Muhidin",
      "lastName": "Hujdur",
      "position": "Stručnjak iz prakse",
      "email": "muhidin.hujdur@etf.unsa.ba",
      "department": "Automatika i elektronika",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/muhidin.hujdur.en.pdf"
    },
    {
      "id": 116,
      "firstName": "Alvin",
      "lastName": "Huseinović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "alvin.huseinovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/alvin.huseinovic.en.pdf"
    },
    {
      "id": 117,
      "firstName": "Belma",
      "lastName": "Ibrahimović",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "belma.ibrahimovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/belma.ibrahimovic.en.pdf"
    },
    {
      "id": 118,
      "title": "mr. sc.",
      "firstName": "Lejla",
      "lastName": "Kadrić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "lejla.kadric@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/lejla.kadric.en.pdf"
    },
    {
      "id": 119,
      "firstName": "Muamer",
      "lastName": "Kafadar",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "muamer.kafadar@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/muamer.kafadar.en.pdf"
    },
    {
      "id": 120,
      "firstName": "Esma",
      "lastName": "Kafedžić",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "esma.kafedzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/esma.kafedzic.en.pdf"
    },
    {
      "id": 121,
      "firstName": "Adna",
      "lastName": "Kozić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "adna.kozic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/adna.kozic.en.pdf"
    },
    {
      "id": 122,
      "firstName": "Irfan",
      "lastName": "Kriještorac",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "irfan.krijestorac@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/irfan.krijestorac.en.pdf"
    },
    {
      "id": 123,
      "firstName": "Vedad",
      "lastName": "Letić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "vedad.letic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/vedad.letic.en.pdf"
    },
    {
      "id": 124,
      "firstName": "Orhan",
      "lastName": "Ljubunčić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "orhan.ljubuncic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/orhan.ljubuncic.en.pdf"
    },
    {
      "id": 125,
      "firstName": "Halid",
      "lastName": "Matoruga",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "halid.matoruga@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/halid.matoruga.en.pdf"
    },
    {
      "id": 126,
      "firstName": "Mirza",
      "lastName": "Matoruga",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "mirza.matoruga@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirza.matoruga.en.pdf"
    },
    {
      "id": 127,
      "title": "mr. sc.",
      "firstName": "Zoran",
      "lastName": "Memić",
      "position": "Stručnjak iz prakse",
      "department": "Telekomunikacije",
      "email": "zoran.memic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zoran.memic.en.pdf"
    },
    {
      "id": 128,
      "title": "dr. sc.",
      "firstName": "Ajla",
      "lastName": "Merzić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "ajla.merzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/ajla.merzic.en.pdf"
    },
    {
      "id": 129,
      "firstName": "Marina",
      "lastName": "Miličević",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "marina.milicevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/marina.milicevic.en.pdf"
    },
    {
      "id": 130,
      "title": "mr. sc.",
      "firstName": "Mirza",
      "lastName": "Milišić",
      "position": "Stručnjak iz prakse",
      "department": "Telekomunikacije",
      "email": "mirza.milisic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirza.milisic.en.pdf"
    },
    {
      "id": 131,
      "title": "dr. sc.",
      "firstName": "Alija",
      "lastName": "Muharemović",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "alija.muharemovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/alija.muharemovic.en.pdf"
    },
    {
      "id": 132,
      "firstName": "Faris",
      "lastName": "Mujkić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "faris.mujkic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/faris.mujkic.en.pdf"
    },
    {
      "id": 133,
      "firstName": "Mahir",
      "lastName": "Muratović",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "mahir.muratovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mahir.muratovic.en.pdf"
    },
    {
      "id": 134,
      "firstName": "Sabina",
      "lastName": "Muratović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "sabina.muratovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sabina.muratovic.en.pdf"
    },
    {
      "id": 135,
      "firstName": "Enil",
      "lastName": "Pajić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "enil.pajic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/enil.pajic.en.pdf"
    },
    {
      "id": 136,
      "firstName": "Sumeja",
      "lastName": "Porča",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "sumeja.porca@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/sumeja.porca.en.pdf"
    },
    {
      "id": 137,
      "firstName": "Iris",
      "lastName": "Salihbegović",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "iris.salihbegovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/iris.salihbegovic.en.pdf"
    },
    {
      "id": 138,
      "firstName": "Mersiha",
      "lastName": "Samardžić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "mersiha.samardzic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mersiha.samardzic.en.pdf"
    },
    {
      "id": 139,
      "firstName": "Franjo",
      "lastName": "Šarčević",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "franjo.sarcevic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/franjo.sarcevic.en.pdf"
    },
    {
      "id": 140,
      "title": "mr. sc.",
      "firstName": "Nerma",
      "lastName": "Šečić-Haračić",
      "position": "Stručnjak iz prakse",
      "department": "Telekomunikacije",
      "email": "nerma.secic-haracic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/nerma.secic-haracic.en.pdf"
    },
    {
      "id": 141,
      "firstName": "Slobodan",
      "lastName": "Sekulović",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "slobodan.sekulovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/slobodan.sekulovic.en.pdf"
    },
    {
      "id": 142,
      "firstName": "Meliha",
      "lastName": "Selak",
      "position": "Stručnjak iz prakse",
      "department": "Automatika i elektronika",
      "email": "meliha.selak@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/meliha.selak.en.pdf"
    },
    {
      "id": 143,
      "firstName": "Haris",
      "lastName": "Šemić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "haris.semic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/haris.semic.en.pdf"
    },
    {
      "id": 144,
      "firstName": "Irena",
      "lastName": "Serna-Marjanović",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "irena.serna-marjanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/irena.serna-marjanovic.en.pdf"
    },
    {
      "id": 145,
      "firstName": "Amer",
      "lastName": "Smajkić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "amer.smajkic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/amer.smajkic.en.pdf"
    },
    {
      "id": 146,
      "firstName": "Haris",
      "lastName": "Smajlagić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "haris.smajlagic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/haris.smajlagic.en.pdf"
    },
    {
      "id": 147,
      "firstName": "Zubejda",
      "lastName": "Suljić",
      "position": "Stručnjak iz prakse",
      "department": "Elektroenergetika",
      "email": "zubejda.suljic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/zubejda.suljic.en.pdf"
    },
    {
      "id": 148,
      "title": "mr. sc.",
      "firstName": "Mirza",
      "lastName": "Varatanović",
      "position": "Stručnjak iz prakse",
      "department": "Telekomunikacije",
      "email": "mirza.varatanovic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/mirza.varatanovic.en.pdf"
    },
    {
      "id": 149,
      "firstName": "Elvedina",
      "lastName": "Zulić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "elvedina.zulic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/elvedina.zulic.en.pdf"
    },
    {
      "id": 150,
      "firstName": "Emir",
      "lastName": "Žunić",
      "position": "Stručnjak iz prakse",
      "department": "Računarstvo i informatika",
      "email": "emir.zunic@etf.unsa.ba",
      "phone": "+387 33 250 700",
      "fax": "+387 33 250 725",
      "cv": "http://www.etf.unsa.ba/people/cv/emir.zunic.en.pdf"
    }
  ]

  constructor() { }

  getStaffMembers() {
    return {
      emeritusProfessors: this.staffMembers.filter(member => member.position === "Emeritus profesor"),
      professors: this.staffMembers.filter(member => member.position === "Redovni profesor"),
      associateProfessors: this.staffMembers.filter(member => member.position === "Vanredni profesor"),
      assistantProfessors: this.staffMembers.filter(member => member.position === "Docent"),
      seniorAssistants: this.staffMembers.filter(member => member.position === "Viši asistent"),
      teachingAssistants: this.staffMembers.filter(member => member.position === "Asistent"),
      industryExperts: this.staffMembers.filter(member => member.position === "Stručnjak iz prakse")
    };
  }

  getDeanOfficeMembers(): StaffMember[] {
    return this.staffMembers.filter(member => member.specialTitle);
  }

  public getStaffMemberById(id: number): StaffMember {
    const member = this.staffMembers.find(member => member.id === id);
    return member ? member : null;
  }
}
